### ISSUE TITLE
Gerenciamento de estado (atributo Busy da classe ViewModel de Login) não está provendo uma UX adequada

### ISSUE THREAD

**Issue by viniciustavanoferreira** [tennismobileapplication/app#29]
Ao buscar realizar um teste unitário e manual positivo na aplicação, visando viabilizar o acesso do usuário (login), o progress indicator é retirado da exibição, exibindo o botão de login novamente, antes da navegação LoginPage -> WelcomePage acontecer:

![image](https://user-images.githubusercontent.com/4478387/80915133-85b92b00-8d26-11ea-9c78-ce50d15813e3.png)
**Página de Login**

![image](https://user-images.githubusercontent.com/4478387/80915144-9b2e5500-8d26-11ea-8ee5-7e584f6fa370.png)
**Progress indicator sendo processado em função do SetState() na View**

![image](https://user-images.githubusercontent.com/4478387/80915157-b731f680-8d26-11ea-8876-25480c6cdb4f.png)
**Momento de navegação entre as Views, exibindo o botão de logar antes do processo**

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar ProgressIndicator em Login](https://trello.com/c/MOSzkAA9/52-adicionar-progressindicator-em-login)

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gerenciamento de estado em Login não provê UX adequada (ProgressIndicator)](https://trello.com/c/3mMnxbaw/56-gerenciamento-de-estado-em-login-n%C3%A3o-prov%C3%AA-ux-adequada-progressindicator)

**Comment by tennismobileapplication** [comment]
Resolvido em #43 .
