### ISSUE TITLE
Regex para password em Login não está validando alguns caracteres especiais.

### ISSUE THREAD

**Issue by tennismobileapplication** [tennismobileapplication/app#31]
No método público validatePassword() do controller da view Login possui o seguinte regex implementado:
![image](https://user-images.githubusercontent.com/63162904/80916051-a7b5ac00-8d2c-11ea-9a08-137870de0323.png)

Entretanto, tal regex não interpreta todo os caracteres especiais que poderão fazer parte de uma senha de usuário:
![image](https://user-images.githubusercontent.com/63162904/80916067-c9169800-8d2c-11ea-9804-67bbb29cb265.png)

**Comment by viniciustavanoferreira** [comment]
Corrigido em #41 .

**Comment by tennismobileapplication** [comment]
Corrigido em #41 .

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [REGEX no Controller de Login (User and Password)](https://trello.com/c/U1plJ2Ft/54-regex-no-controller-de-login-user-and-password)
