### ISSUE TITLE
ProgressIndicator na view RegisterUser não está sendo tratada

### ISSUE THREAD

**Issue by viniciustavanoferreira** [tennismobileapplication/app#34]
Apesar do atributo busy na classe RegisterUserViewModel existir, o ProgressIndicator não está sendo gerado através de SetState() na view RegisterUser em função de RegisterUserViewModel.busy.
![image](https://user-images.githubusercontent.com/4478387/80978425-67bdfa00-8dfc-11ea-8f7f-de3bc22ea236.png)

**Comment by viniciustavanoferreira** [comment]
Corrigido em #39 .

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar ProgressIndicator em RegisterUser](https://trello.com/c/3vyjFkDY/53-adicionar-progressindicator-em-registeruser)

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar ProgressIndicator em RegisterUser](https://trello.com/c/3vyjFkDY/53-adicionar-progressindicator-em-registeruser)
