### ISSUE TITLE
POST em USER sendo feito em RegisterUser

### ISSUE THREAD

**Issue by viniciustavanoferreira** [tennismobileapplication/app#37]
Atualmente, a requição HTTP POST (controller + repository) responsável por criar um novo usuário está sendo invocada da view RegisterUser:
![image](https://user-images.githubusercontent.com/4478387/80978996-267a1a00-8dfd-11ea-8a3b-61963327f00b.png)

É necessário refatorar tal implementação para viabilizar sua invocação da view PhonePage.

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementação do cadastro de usuário (POST - User)](https://trello.com/c/OoszdCyI/50-implementa%C3%A7%C3%A3o-do-cadastro-de-usu%C3%A1rio-post-user)

**Comment by tennismobileapplication** [comment]
Resolvido em #48 .
