### ISSUE TITLE
Busca equivocada do texto puro de input em RegisterUser de maneira

### ISSUE THREAD

**Issue by viniciustavanoferreira** [tennismobileapplication/app#38]
Atualmente, o texto atribuído pelo usuário na view RegisterUser está sendo controlado por TextEditingControllers correspondentes aos widgets criados:
![image](https://user-images.githubusercontent.com/4478387/80979363-a0120800-8dfd-11ea-9741-d63fd6e8fd30.png)

Isso gera atribuição de valor que não corresponde ao input implícito:
![image](https://user-images.githubusercontent.com/4478387/80979473-c3d54e00-8dfd-11ea-86e9-15a3d12747cc.png)

**Comment by tennismobileapplication** [comment]
Resolvido em #42 .

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Busca equivocada do texto puro de input em RegisterUser](https://trello.com/c/YveEKG1l/55-busca-equivocada-do-texto-puro-de-input-em-registeruser)
