### ISSUE TITLE
Falta de ProgressIndicator em PasswordRecovery.View

### ISSUE THREAD

**Issue by viniciustavanoferreira** [tennismobileapplication/app#46]
![image](https://user-images.githubusercontent.com/4478387/82386615-399b0580-9a0b-11ea-9338-5f4d1059d44b.png)

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementação do PasswordRecovery (POST - Recover)](https://trello.com/c/fO9PthsD/57-implementa%C3%A7%C3%A3o-do-passwordrecovery-post-recover)

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementação do PasswordRecovery (POST - Recover)](https://trello.com/c/fO9PthsD/57-implementa%C3%A7%C3%A3o-do-passwordrecovery-post-recover)

**Comment by tennismobileapplication** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementação do ProgressIndicator em PasswordRecovery.view](https://trello.com/c/93iTpWhv/58-implementa%C3%A7%C3%A3o-do-progressindicator-em-passwordrecoveryview)

**Comment by viniciustavanoferreira** [comment]
Resolvido em #47 .

**Comment by tennismobileapplication** [comment]
Resolvido em #47 .
